### ISSUE TITLE
Error: g-dbus-error-quark

### ISSUE THREAD

**Issue by kynikos** [kynikos/outspline#378]
This has started happening during the activation of an alarm, probably after a recent update to a system library?

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/outspline/coreaux/__init__.py", line 96, in run_with_excepthook
    run_old(*args, **kw)
  File "/usr/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/outspline/extensions/organism_timer/timer.py", line 555, in _activate_occurrences_block
    self._activate_occurrences(time, occsd)
  File "/usr/lib/python2.7/site-packages/outspline/extensions/organism_timer/timer.py", line 559, in _activate_occurrences
    activate_occurrences_event.signal(time=time, occsd=occsd)
  File "/usr/lib/python2.7/site-packages/outspline/coreaux/events.py", line 40, in signal
    handler(kwargs)
  File "/usr/lib/python2.7/site-packages/outspline/extensions/organism_alarms/__init__.py", line 214, in _handle_activate_occurrences
    occsd[filename])
  File "/usr/lib/python2.7/site-packages/outspline/extensions/organism_alarms/alarmsmod.py", line 182, in activate_alarms
    self._activate_alarm(occ)
  File "/usr/lib/python2.7/site-packages/outspline/extensions/organism_alarms/alarmsmod.py", line 213, in _activate_alarm
    alarm=alarm['alarm'])
  File "/usr/lib/python2.7/site-packages/outspline/coreaux/events.py", line 40, in signal
    handler(kwargs)
  File "/usr/lib/python2.7/site-packages/outspline/plugins/notify/__init__.py", line 88, in _handle_alarm
    self.alarm.show()
Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.Notifications exited with status 1 (25)
```

My last system update:
```
[2015-12-30 01:23] [ALPM] upgraded lib32-libdrm (2.4.65-1 -> 2.4.66-1)
[2015-12-30 01:23] [ALPM] upgraded libpng (1.6.19-1 -> 1.6.20-1)
[2015-12-30 01:23] [ALPM] upgraded libldap (2.4.42-2 -> 2.4.43-1)
[2015-12-30 01:23] [ALPM] upgraded libva (1.6.1-1 -> 1.6.2-1)
[2015-12-30 01:23] [ALPM] upgraded lib32-libva (1.6.1-1 -> 1.6.2-1)
[2015-12-30 01:23] [ALPM] upgraded libcdr (0.1.1-4 -> 0.1.2-1)
[2015-12-30 01:23] [ALPM] upgraded libwpg (0.3.0-2 -> 0.3.1-1)
[2015-12-30 01:23] [ALPM] upgraded mesa (11.1.0-1 -> 11.1.0-2)
[2015-12-30 01:23] [ALPM] upgraded pavucontrol (3.0-2 -> 3.0-3)
[2015-12-30 01:23] [ALPM] upgraded python2-ipaddress (1.0.15-1 -> 1.0.16-1)
[2015-12-30 01:23] [ALPM] upgraded rsync (3.1.1-4 -> 3.1.2-1)
```

**Comment by kynikos** [comment]
The problem is in the `notify` plugin. Try implementing #125?

**Comment by kynikos** [comment]
This was only a duplicate of #376 in the end...
